DROP TABLE IF EXISTS `REPORT`;
DROP TABLE IF EXISTS `REPORT_CABINET`;
DROP TABLE IF EXISTS `ID_TABLE`;

CREATE TABLE `ID_TABLE` (
  `ID_NAME` varchar(128) NOT NULL,
  `ID_HI` int(10) NOT NULL,
  `ID_LO` int(10) NOT NULL DEFAULT '1',
  `INTERVAL` int(10) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('REPORT_CABINET_ID', 0, 4, 1);
INSERT INTO `ID_TABLE` (`ID_NAME`, `ID_HI`, `ID_LO`, `INTERVAL`) VALUES ('REPORT_ID', 0, 4, 1);

CREATE TABLE `REPORT_CABINET` (
   `ID`            int(10) NOT NULL,
   `NAME`          varchar(128),
   `DESCRIPTION`   varchar(1024),
   `PARENT_ID`     int(10),
   PRIMARY KEY (`ID`),
   CONSTRAINT `FK_REPORT_CABINET_PARENT_ID` FOREIGN KEY (`PARENT_ID`) REFERENCES `REPORT_CABINET` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `REPORT` (
   `ID`                  int(10) NOT NULL,
   `NAME`                varchar(128),
   `DESCRIPTION`         varchar(1024),
   `LOCATION`            varchar(1024),
   `REPORT_CABINET_ID`   int(10),
   PRIMARY KEY (`ID`),
   CONSTRAINT `FK_REPORT_CABINET_ID` FOREIGN KEY (`REPORT_CABINET_ID`) REFERENCES `REPORT_CABINET` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
